// Generated by scripts/sync-model-catalog.js. Keep a checked-in snapshot so
// the public catalog works before a user has configured credentials.
export const minimaxTextModelIds = Object.freeze([
  'MiniMax-M3',
  'MiniMax-M2.7',
  'MiniMax-M2.7-highspeed',
  'MiniMax-M2.5',
  'MiniMax-M2.5-highspeed',
  'MiniMax-M2.1',
  'MiniMax-M2.1-highspeed',
  'MiniMax-M2',
]);
